init.js

Check build script before running it and remove try catch.

update init script

---

packages/redux/package.json
packages/redux/src/index.js
yarn.lock

redux-tools has already full support for ImmutableJS.
ref: 
- https://github.com/reduxjs/redux-devtools/issues/283#issuecomment-271974212
- https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.12.1
screenshot (local):

feat: add redux-devtools support

---

packages/ui-components/src/Tabs/Tabs.js

**before**
https://user-images.githubusercontent.com/20736452/144200606-99f99511-bf26-47dd-a117-43030cf976b3.mov
**after**
https://user-images.githubusercontent.com/20736452/144200633-64e69a36-9c6d-4456-b562-90fb159ea9b4.mov

fix: file tab can not reopen correctly after close

---

packages/filetree/package.json
packages/navbar/package.json
packages/ui-components/package.json
packages/ui-components/src/Tabs/TabContextMenu.js
packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/Tabs.js
yarn.lock

the tab drag effect:
https://user-images.githubusercontent.com/20736452/144560297-f0fa969e-196c-4d71-a575-d53cd8beea20.mov

feat: add sort support for file tab

---

packages/ui-components/src/Tabs/TabHeader.js

**before**
https://user-images.githubusercontent.com/20736452/145360665-c9a9591d-b63d-4f3b-bbda-d4fad7cd5a4a.mov
**after**
https://user-images.githubusercontent.com/20736452/145360845-4addbae1-ac25-47b0-84b8-5894f827dbaf.mov

perf: improve file tab drag effect

---

packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/styles.scss

now, it will scroll horizontally when the tab text is too long in the container.
Note: may improve the UI of the scroller of the container

fix: tab with long text will be broken

---

packages/filetree/src/index.js

https://user-images.githubusercontent.com/20736452/145785466-a8cbc9e0-83ee-46b0-9e44-8b729d742e00.mov

perf: add node loading effect for file tree

---

packages/ui-components/src/Tabs/TabHeader.js

- move the event to the root
- disable the context menu animation

fix: file tab click area

---

packages/filetree/src/index.js
packages/filetree/src/styles.css

feat: less spacing with file tree

---

packages/file-ops/src/ElectronFileOps.js

Open options are faild when the path is not exsist

fix: context menu event of project nav bar

---

packages/keypair/src/CreateKeypairModal.js
packages/keypair/src/ImportKeypairModal.js
packages/keypair/src/KeypairManagerModal.js
packages/keypair/src/RevealSecretModal.js

formating address in the Keypair Manager

feat: improve address formatting in keypair manage

---

.idea/.gitignore
.idea/aws.xml
.idea/electron-components.iml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
packages/code-editor/src/CodeEditorCollection.js
packages/keypair/src/CreateKeypairModal.js
packages/keypair/src/ImportKeypairModal.js
packages/keypair/src/KeypairInputSelector.js
packages/keypair/src/KeypairManagerModal.js
packages/keypair/src/KeypairSelector.js
packages/keypair/src/RevealSecretModal.js
packages/keypair/src/keypairManager.js
packages/ui-components/src/Tabs/NavigationBar.js
packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/TabbedExplorer.js
packages/ui-components/src/Tabs/styles.scss
packages/ui-components/src/inputs/DropdownInput.js

address format for RPC-Client part

feat: address format for RPC-Client

---

packages/ui-components/src/Tabs/styles.scss

change the location of puls sign in nav bar

perf(styles.scss): change the location of puls sign in nav bar

---

packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/styles.scss

perf: can use scroll wheel in windows

perf: can use scroll wheel in windows

---

packages/ui-components/package.json
packages/ui-components/src/Scrollbar/index.js
packages/ui-components/src/Tabs/TabHeader.js

add react-custom-scrollbars-2 lib, optimizing scroll function for tab

feat: beautify tab scroll effect

---

packages/ui-components/src/Scrollbar/index.js

delete redundant code of scrollbar.

fix: delete redundant code of scrollbar.

---

packages/ui-components/src/Scrollbar/index.js

handle error with prevent default.

fix(Scrollbar): handle error with prevent default.

---

packages/ui-components/src/Modal.js
packages/workspace/src/components/NewProjectModal.js

Need to merge together with https://github.com/ObsidianLabs/eth-components/pull/35

Use bootstrap defined classes for modals

---

packages/ui-components/src/Tabs/TabHeader.js

now there are two way to open tab:
*  click to open tab, it means when you mouse is up the tab will be opened.
*  the tab will open when it was dropped.

feat(TabHeader): change how to open tab.

---

packages/code-editor/src/CodeEditorCollection.js
packages/code-editor/src/MonacoEditor/MonacoEditor.js
packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js
packages/code-editor/src/customTabs/Markdown/index.js
packages/docker/src/DockerImageInputSelector.js
packages/filetree/src/index.js
packages/terminal/src/index.js
packages/ui-components/src/buttons/ToolbarButton.js
packages/ui-components/src/inputs/DropdownInput.js
packages/workspace/src/ProjectManager/RemoteProjectManager.js
packages/workspace/src/components/Workspace.js

feat: switch readonly mode while opening others project

feat: switch readonly mode while opening others project

---

packages/ui-components/src/Tabs/TabHeader.js

when there is only one tab left, hidden tab's close button.

feat: last tab cant close

---

packages/keypair/src/KeypairManagerModal.js

format address for keypair manager.

feat(KeypairManagerModal): format address for keypair manager.

---

packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/Tabs.js

scroll the tab into view when it was clicked.

feat(Tab): scroll the tab into view when it was clicked.

---

packages/keypair/src/KeypairInputSelector.js

filters are now no longer case sensitive.

feat(keypairManagerModal): perfect keypair filter.

---

packages/ui-components/src/Tabs/NavigationBar.js

format address in input after component updated.

feat(NavigationBar): format address in input after component updated.

---

packages/auth/src/Auth.js
packages/auth/src/providers/index.js
packages/auth/src/providers/nouser.js
packages/code-editor/src/customTabs/Markdown/index.js
packages/filetree/src/index.js
packages/ui-components/src/styles/index.scss
packages/workspace/src/ProjectManager/RemoteProjectManager.js

improve toggle public and private.

feat: improve toggle public and private

---

packages/ui-components/src/Tabs/styles.scss

remove actived tab's hover style.

feat(TabHeader): remove hover style.

---

packages/ui-components/src/Scrollbar/index.js

change transition with ease-in-out.

feat(Scrollbar): change transition with ease-in-out.

---

packages/code-editor/src/CodeEditorCollection.js
packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/Tabs.js

when the last tab closed, add a new tab. and you can't clo…se the last tab which is a new tab.

feat(Tab): handle last tab interaction.

---

packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/styles.scss

now when a tab is dragging, hover is no more.

feat(TabHeader): optimize tab hover.

---

packages/ui-components/src/Tabs/TabHeader.js

add click callback for every tab.

perf(TabHeader): add click callback for every tab.

---

packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/styles.scss

don't change last tab's width.

feat(TabHeader): don't change last tab's width.

---

packages/ui-components/src/Tabs/styles.scss

feat(TabHeader): center the word.

---

packages/ui-components/src/Tabs/TabHeader.js
packages/ui-components/src/Tabs/styles.scss

fix(TabHeader): fix hover flicker.

---

packages/keypair/src/KeypairInputSelector.js

format Authorization's address.

feat(KeypairInputSelector): format address.

---

packages/navbar/src/NavLinkRight.js

feat: show fullname on navbar

---

packages/code-editor/src/MonacoEditor/modelSessionManager/index.js
packages/ui-components/src/Tabs/TabHeader.js
packages/workspace/src/ProjectManager/LocalProjectManager.js
packages/workspace/src/ProjectManager/RemoteProjectManager.js

feat: improve move delete file action

feat: improve move delete file action

---

packages/code-editor/src/customTabs/Markdown/index.js

fixup! toogle public and private

fixup! toogle public and private

---

packages/keypair/src/KeypairInputSelector.js
packages/keypair/src/KeypairManagerModal.js
packages/keypair/src/KeypairSelector.js
packages/keypair/src/keypairManager.js
packages/keypair/src/redux/index.js

feat: upgrade keypair detail model

feat: upgrade keypair detail model

---

packages/i18n/src/locales/en.js
packages/i18n/src/locales/zh.js
packages/navbar/src/User.js
packages/user/src/UserHomepage.js
packages/workspace/src/components/CreateFileOrFolderModals.js
packages/workspace/src/components/TutorialModal.js
packages/workspace/src/index.js
packages/workspace/src/styles.scss

new features: 
* show tutorial modal when the user first visits the website
* add 'Help Page' tab to dropdown navBar
code modification:
*  create caches in localstorage to verify if it's the first time 
*  create tutorial modal
*  insert tutorial modal in user/UserHomepage.js 
*  add Help Page tab in  navBar/User.js
undo:
* need to update the link address for the guide page 
* need Chinese version of description

feat: add the tutorial modal for first visit user

---

packages/navbar/src/NavDropdown.js
packages/ui-components/src/inputs/DebouncedInput.js
packages/ui-components/src/inputs/DropdownInput.js
packages/ui-components/src/styles/index.scss

modify  part of the mouse hover style, the current modified part is, project deploy modal

fix: unified mouse hover style

---

packages/code-editor/src/MonacoEditor/MonacoEditor.js
packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/MonacoEditor/modelSessionManager/index.js
packages/filetree/src/index.js
packages/filetree/src/statusTitle.js
packages/filetree/src/styles.css
packages/workspace/src/components/Workspace.js

features:
it will show the dynamic title of the file, including the above situation
* open file folder
* after each time compiling
modify:
* create statusTitle component
* component will receive a message after compiling

feat: display fileTree error status

---

packages/keypair/src/KeypairInputSelector.js
packages/keypair/src/KeypairManagerModal.js
packages/keypair/src/keypairManager.js
packages/navbar/src/NavLinkRight.js
packages/notification/src/manager.js
packages/ui-components/src/Modal.js

fix: keypair bugs

---

packages/navbar/src/User.js
packages/user/src/UserHomepage.js
packages/workspace/src/components/TutorialModal.js

feat: ethereum studio name change some pop-ups and titles changed names

---

package.json
packages/keypair/src/KeypairManagerModal.js
packages/keypair/src/KeypairSelector.js
packages/keypair/src/keypairManager.js
yarn.lock

fix: fix keypiar bugs

---

packages/file-ops/src/AwsS3Fs.js
packages/filetree/rollup.config.js
packages/filetree/src/helper.js
packages/filetree/src/index.js
packages/filetree/src/styles.css
packages/workspace/src/ProjectManager/RemoteProjectManager.js

feat: improve drag style

---

packages/code-editor/src/MonacoEditor/modelSessionManager/index.js
packages/filetree/src/index.js
packages/filetree/src/styles.css
packages/workspace/src/ProjectManager/LocalProjectManager.js
packages/workspace/src/components/ActionConfirm.js
packages/workspace/src/components/Workspace.js
packages/workspace/src/styles.scss

fix: improve fileTree style part 1

---

packages/file-ops/src/AwsS3Fs.js
packages/file-ops/src/ElectronFileOps.js
packages/file-ops/src/WebFileOps.js
packages/filetree/main/FileTreeChannel.js
packages/filetree/main/FileTreeClient.js
packages/filetree/src/index.js
packages/workspace/src/ProjectManager/LocalProjectManager.js
packages/workspace/src/ProjectManager/RemoteProjectManager.js
packages/workspace/src/components/Workspace.js

fix: update fileTree event part1

---

packages/filetree/src/helper.js
packages/filetree/src/index.js
packages/workspace/src/components/Workspace.js

fix: update fileTree event part 2

---

packages/code-editor/src/MonacoEditor/MonacoEditor.js
packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js
packages/file-ops/src/ElectronFileOps.js
packages/filetree/package.json
packages/filetree/src/helper.js
packages/filetree/src/hooks/useBatchLoad.js
packages/filetree/src/index.js
packages/workspace/src/ProjectManager/LocalProjectManager.js
packages/workspace/src/components/Workspace.js
packages/workspace/src/components/contextMenu.js

Feat: file tree keypress

---

packages/filetree/src/helper.js
packages/filetree/src/index.js
packages/ui-components/src/Tabs/TabsWithNavigationBar.js
packages/workspace/src/components/Workspace.js

Fix: filetree-sync-data-with-codeEditor

---

packages/workspace/src/ProjectManager/LocalProjectManager.js

fix: default-file-projectManager

---

packages/auth/src/Auth.js
packages/auth/src/providers/github.js
packages/auth/src/providers/index.js

fix: refactor auth module code

---

packages/filetree/src/index.js

fix: dispaly public file in filetree

---

packages/code-editor/src/customTabs/Markdown/index.js

fix: markdown-custom-tab-save

---

packages/code-editor/src/customTabs/Markdown/index.js

Fix: set public or private failed

---

packages/workspace/src/components/Workspace.js

-[x] fix: project setting button no response

fix: projectSetting button no response

---

packages/filetree/package.json

fix: upgrade hotkeys dependency

---

packages/redux/src/index.js

- fix: hiden edit button on share status (#260)
- fix: handle redux error

fix: handle redux error and show in console

---

packages/code-editor/src/CodeEditorCollection.js
packages/code-editor/src/MonacoEditor/CustomTabContainer.js
packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js
packages/code-editor/src/MonacoEditor/modelSessionManager/index.js
packages/code-editor/src/customTabs/Markdown/index.js

feat: resolove issue with edit markdown file aftern switch share button

---

packages/ui-components/src/buttons/DropdownToolbarButton.js
packages/ui-components/src/buttons/ToolbarButton.js

fix: hiden project button while sharing

---

packages/code-editor/src/MonacoEditor/modelSessionManager/index.js

fix: file not updated after edit file and switch sharing status

---

packages/code-editor/src/MonacoEditor/CustomTabContainer.js
packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js

Fix: save shortcut sync

---

packages/keypair/src/KeypairInputSelector.js
packages/navbar/src/NavDropdown.js
packages/navbar/src/NavLinkRight.js
packages/navbar/src/index.js
packages/ui-components/src/inputs/DropdownInput.js

Feat: add metamask option

---

packages/code-editor/src/customTabs/Markdown/index.js
packages/code-editor/src/styles.scss
packages/i18n/src/locales/en.js
packages/i18n/src/locales/zh.js

feat: add tourist mode in markdown file

---

packages/keypair/src/KeypairInputSelector.js

fix: matamsk lock account cause webpage crash

---

packages/filetree/src/index.js

fix: upgrade handleSetActive methods in filetree

---

packages/i18n/src/locales/en.js
packages/i18n/src/locales/zh.js
packages/workspace/src/components/Workspace.js

Fix: shared projct deploy failed notification

---

packages/navbar/src/NavDropdown.js
packages/navbar/src/NavLinkContent.js
packages/navbar/src/NavLinkRight.js
packages/navbar/src/index.js
packages/navbar/src/styles.scss

feat: adjust network drop-down list UI interface

---

packages/ui-components/src/ported/Badge.js
packages/ui-components/src/ported/Container.js
packages/ui-components/src/ported/Jumbotron.js

Companion PR: https://github.com/ObsidianLabs/Black-IDE/pull/97

fix(tailwind): add prefix to tailwind-made components

---

packages/code-editor/src/MonacoEditor/MonacoEditor.js
packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js
packages/code-editor/src/MonacoEditor/modelSessionManager/breadcrumb-data.js
packages/code-editor/src/MonacoEditor/modelSessionManager/index.js
packages/code-editor/src/styles.scss

https://user-images.githubusercontent.com/6639067/185281893-89d023af-a2c1-45c7-bfa2-e57af909c746.mov

feat: add breadcrumb bar

---

packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js
packages/code-editor/src/styles.scss

fix: fix breadcrumb bar style

---

packages/code-editor/package.json
packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js
packages/code-editor/src/styles.scss

https://user-images.githubusercontent.com/6639067/186386538-8ae61663-6704-4d3b-97f8-87166b9d66b4.mov

fix: update ast bar

---

packages/code-editor/src/MonacoEditor/modelSessionManager/MonacoEditorModelSession.js

change logic from AST parse to keyword match.
AST parser may cause parse error and performance problem.

fix: change logic from ast to grep match

---

packages/code-editor/src/MonacoEditor/MonacoEditorContainer.js
packages/code-editor/src/styles.scss

https://user-images.githubusercontent.com/6639067/187331144-2fef7512-03ef-4d55-8ae6-8475e9ad1425.mov

feat: ast bar add filetree
